### ISSUE TITLE
bank2ynab

### ISSUE THREAD

**Issue by torbengb** [scottrobertson/awesome-ynab#12]
Hi Scott! I didn't know about this repo, or I would have submitted this earlier: 

"bank2ynab" is a common project to consolidate all conversion efforts from various banks' export formats into YNAB's import format. It currently supports 50 formats from all over the world, and more are being added all the time. 

Read more: https://github.com/bank2ynab/bank2ynab#bank2ynab

**Comment by scottrobertson** [comment]
@torbengb feel free to submit a PR :)
