### ISSUE TITLE
New project: You Need A Parser

### ISSUE THREAD

**Issue by leolabs** [scottrobertson/awesome-ynab#9]
Link: https://ynap.leolabs.org
GitHub: https://github.com/leolabs/you-need-a-parser

YNAP converts CSV files from a variety of (German, for now) banks and apps into a format that can easily be imported into You Need A Budget. YNAP is free and open-source and your files never leave your browser.

Currently, YNAP supports Outbank, N26, ING-DiBa, comdirect, Kontist. More formats are already in the making.

**Comment by scottrobertson** [comment]
Submit a pull request :)

**Comment by leolabs** [comment]
Is there a rule for where I should add my project? Should I add it to the end or beginning of the list or is there a specific order that I should respect?

**Comment by scottrobertson** [comment]
@leolabs I generally just add them to the bottom 👍 

One suggestion for the project. If you are unable to find a parser, maybe fall back to something like this from my app: ![](https://scottrobertson-drops.ams3.digitaloceanspaces.com/O5XouhN.jpg)

http://halloffame.github.io/ynab-csv/ also does it like that.

**Comment by leolabs** [comment]
That's a great idea! I'll try to implement that and make it as smart as possible so the user doesn't have to assign fields to their YNAB equivalent manually, if possible.

**Comment by scottrobertson** [comment]
@leolabs plenty of libraries out there for it too. I think i used an adaption of https://github.com/jgile/vue-csv-import, but it was a while ago a built it.
